Feature/addtreeview
FlatMoon/header_hero_tree pull request #1
Opened 2024-07-12 14:06 UTC by FlatMoon

Added a tree view tab.

2024-07-12 20:18 UTC, scfwilson requested changes
I've added some comments. Read them and make the changes suggested. Then commit them. The pull request (PR) will automatically update and I will be notified. Then I can review it again.

2024-07-12 20:18 UTC, scfwilson commented on header_hero/Windows/ProgressDialog.cs
> +            progressBar.Value = _feedback.Item%2856;
What's %2856? Has it been added by accident?

2024-07-12 20:18 UTC, scfwilson commented on header_hero/Windows/ReportForm.cs
> +//using static System.Windows.Forms.VisualStyles.VisualStyleElement;
Remove this commented out code

2024-07-12 20:18 UTC, scfwilson commented on header_hero/Windows/ReportForm.cs
> +        TreeNode currentNode = null;
Should this be outside a method?

2024-07-12 20:18 UTC, scfwilson commented on header_hero/Windows/ReportForm.cs
> +;
Remove this and the one on line 81.

2024-07-12 20:18 UTC, scfwilson commented on header_hero/Windows/ReportForm.cs
> +                    try
If you're not going to catch the Exception then remove the try catch block.

2024-07-15 19:47 UTC, FlatMoon commented on header_hero/Windows/ReportForm.cs
> +        TreeNode currentNode = null;
I think so, because it needs to be accessed by more than one method. Or should I declare it as public instead?

2024-07-15 19:48 UTC, FlatMoon commented on header_hero/Windows/ProgressDialog.cs
> +            progressBar.Value = _feedback.Item%2856;
Was there for debugging but no longer needed, so I have removed it.

2024-07-15 19:56 UTC, scfwilson commented on header_hero/Windows/ReportForm.cs
> +        TreeNode currentNode = null;
You should declare it public and put it at the top of the class.

2024-07-15 20:08 UTC, FlatMoon commented on header_hero/Windows/ReportForm.cs
> +        TreeNode currentNode = null;
That has seemed to give errors to the rest of the code, saying that things "do not exist in the current context"

2024-07-15 20:11 UTC, FlatMoon commented on header_hero/Windows/ReportForm.cs
> +        TreeNode currentNode = null;
Nevermind! I misunderstood where I was placing the line.

2024-07-16 15:58 UTC, scfwilson approved these changes
Sorry it took me some time to work out how to see your latest changes, The way it works is different to ADO.

2024-07-16 17:46 UTC, merged